apiVersion: v1
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [auth.anonymous]
    enabled = true
    org_name = Main Org.
    org_role = Admin
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [security]
    allow_embedding = true
    [server]
    domain = ''
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: kubepromstack
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2023-11-20T22:02:05Z"
  labels:
    app.kubernetes.io/instance: kubepromstack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 10.1.5
    helm.sh/chart: grafana-7.0.6
  name: kubepromstack-grafana
  namespace: monitoring
  resourceVersion: "1904"
  uid: e49b4b14-55b2-4270-86ee-15d8a05837e6
